import CommonLoader from '../commonLoader';
import { type ScreenshotFormat } from '../interface';
import type HardPlayer from '.';
export default class VideoLoader extends CommonLoader<HTMLVideoElement> {
    _delayPlay: boolean;
    $canvasElement: HTMLCanvasElement;
    canvasContext: CanvasRenderingContext2D | null;
    trackGenerator: any;
    vwriter: any;
    $videoElement: HTMLVideoElement;
    player: HardPlayer;
    $posterElement: HTMLImageElement;
    _videoMuted: boolean;
    constructor(player: HardPlayer);
    destroy(): void;
    fixChromeVideoFlashBug(): void;
    play(): void;
    _getVideoReadyState(): number;
    _play(): void;
    pause(isNow?: boolean): void;
    clearView(): void;
    screenshot(filename: string, format?: keyof ScreenshotFormat, quality?: number, type?: string): string | File;
    initCanvasViewSize(): void;
    _poster(): void;
    render(msg: any): void;
    resize(): void;
    _resizeElement($Element: HTMLVideoElement | HTMLImageElement): void;
    isPlaying(): boolean;
    get currentTime(): number;
    _enableSoundOnUserInteraction(): void;
}
